language: android
jdk: oraclejdk7

android:
    components:
        - android-21
        - build-tools-21.0.0
        - extra-android-support
    licenses:
        - android-sdk-license-5be876d5

script:
    - make
